<?xml version="1.0" encoding="UTF-8"?>
<customMapSource overlay="true">
<name>Lantmäteriets Terrängskuggning 0.2</name>
<url>https://www.utsidan.se/cltools/gurumaps/uaproxy.php/minkarta.lantmateriet.se/map/hojdmodell/?SERVICE=WMS&amp;VERSION=1.1.1&amp;REQUEST=GetMap&amp;FORMAT=image%2Fpng&amp;TRANSPARENT=true&amp;OPACITY=0.2&amp;LAYERS=terrangskuggning&amp;TILED=true&amp;STYLES=&amp;WIDTH=256&amp;HEIGHT=256&amp;SRS=EPSG%3A3857&amp;BBOX={$bbox}</url>
</customMapSource>
